"""
Unit test suite
generated by claude opus
"""

import numpy as np
import pytest

from traceit import units as u
from traceit.freq import FrequencyGrid


def test_constants():
    assert u.ETA0 == pytest.approx(376.730, abs=1e-3)
    assert u.C0 == 299_792_458
    assert u.C0 == pytest.approx(1 / np.sqrt(u.MU0 * u.EPS0))


def test_lengths():
    assert 1000 * u.MIL == pytest.approx(u.INCH)
    assert u.OZ_CU / u.MIL == pytest.approx(1.37, abs=0.01)


def test_db():
    assert u.db20(0.5) == pytest.approx(-6.0206, abs=1e-4)
    assert u.from_db20(u.db20(0.123)) == pytest.approx(0.123)
    assert np.isfinite(u.db20(0.0))
    assert u.NP_TO_DB == pytest.approx(8.6859, abs=1e-4)


def test_grid_basic():
    g = FrequencyGrid(f_max=50e9, n=5001)
    assert g.f[0] == 0.0
    assert g.f[-1] == 50e9
    assert np.allclose(np.diff(g.f), g.df)
    assert g.df == pytest.approx(10e6)
    assert g.dt == pytest.approx(10e-12)
    assert g.t_window == pytest.approx(100e-9)


def test_grid_from_resolution():
    g = FrequencyGrid.from_resolution(50e9, 10e6)
    assert g.n == 5001
    assert g.df <= 10e6


def test_grid_is_hashable_and_frozen():
    g = FrequencyGrid(1e9, 11)
    assert hash(g) == hash(FrequencyGrid(1e9, 11))
    with pytest.raises(AttributeError):
        g.n = 3  # type: ignore[misc]


@pytest.mark.parametrize("f_max,n", [(0, 10), (-1, 10), (1e9, 1)])
def test_grid_rejects_bad_input(f_max, n):
    with pytest.raises(ValueError):
        FrequencyGrid(f_max, n)
